---
path: github.com/OwnLocal/heka-plugins
deps:
  - loc: https://github.com/OwnLocal/heka.git
    type: git
    ref: v0.9.2-ol1
    path: github.com/mozilla-services/heka

  - loc: github.com/onsi/ginkgo/ginkgo
  - loc: github.com/onsi/gomega
