---
path: github.com/OwnLocal/heka-plugins
deps:
  - loc: https://github.com/OwnLocal/heka.git
    type: git
    ref: google-code-gone-fix
    path: github.com/mozilla-services/heka

  - loc: github.com/onsi/ginkgo/ginkgo
  - loc: github.com/onsi/gomega
  - loc: github.com/hhkbp2/go-strftime
